Repository BinaryStudioAcademy/bsa-2021-codetrainer, pull requests merged in 2021-08, with the labels that each got.

#9 Sign-In page Layout
  client/package-lock.json
  client/package.json
  client/src/assets/icons/cover-background.svg
  client/src/assets/icons/hide.svg
  client/src/assets/icons/logo.svg
  client/src/assets/icons/show.svg
  client/src/components/index.ts
  client/src/components/pages/index.ts
  client/src/components/pages/sign-in/button/button.module.scss
  client/src/components/pages/sign-in/button/index.tsx
  client/src/components/pages/sign-in/config.ts
  client/src/components/pages/sign-in/cover-layout/cover.module.scss
  client/src/components/pages/sign-in/cover-layout/index.tsx
  client/src/components/pages/sign-in/form-field/form-field.module.scss
  client/src/components/pages/sign-in/form-field/index.tsx
  client/src/components/pages/sign-in/index.tsx
  client/src/components/pages/sign-in/password-field/index.tsx
  client/src/components/pages/sign-in/password-field/password-input.module.scss
  client/src/components/pages/sign-in/separator/index.tsx
  client/src/components/pages/sign-in/separator/separator.module.scss
  client/src/components/pages/sign-in/sign-in.module.scss
  client/src/containers/routing/index.tsx
  client/src/containers/sign-in/index.tsx
  client/src/index.tsx
  client/src/typings/sign-in-form.ts
  client/src/typings/webapi.d.ts
Labels: enhancement

#20 Button & Checkbox & Rank Components
  client/src/components/basic/button/button.module.scss
  client/src/components/basic/button/index.tsx
  client/src/components/basic/checkbox/checkbox.module.scss
  client/src/components/basic/checkbox/index.tsx
  client/src/components/basic/index.ts
  client/src/components/basic/rank/config.ts
  client/src/components/basic/rank/helpers.ts
  client/src/components/basic/rank/index.tsx
  client/src/components/basic/rank/rank.module.scss
Labels: enhancement

#4 Add SignUp Page with validation
  client/package-lock.json
  client/src/components/basic/private-route/index.tsx
  client/src/components/common/cover-layout/cover.module.scss
  client/src/components/common/cover-layout/index.tsx
  client/src/components/common/form-input/form-input.module.scss
  client/src/components/common/form-input/index.tsx
  client/src/components/common/index.ts
  client/src/components/index.ts
  client/src/components/pages/index.ts
  client/src/components/pages/sign-in/index.tsx
  client/src/components/pages/sign-up/index.tsx
  client/src/components/pages/sign-up/sign-up.module.scss
  client/src/containers/routing/index.tsx
Labels: enhancement

#2 Added main sidebar
  client/package-lock.json
  client/package.json
  client/src/assets/images/logo.svg
  client/src/components/common/main-sidebar/index.tsx
  client/src/components/common/main-sidebar/main-sidebar.module.scss
  client/src/components/index.ts
  client/src/styles/index.scss
  client/src/styles/normalize.scss
Labels: enhancement

#15 Added component Header, Avatar and Label (for rank and mark)
  client/src/assets/icons/header/bell.svg
  client/src/assets/icons/header/menu/avatar.svg
  client/src/assets/icons/header/menu/goal.svg
  client/src/assets/icons/header/menu/logout.svg
  client/src/assets/icons/header/menu/settings.svg
  client/src/assets/images/header/avatar.png
  client/src/assets/images/header/default-avatar.png
  client/src/components/basic/avatar/avatar.module.scss
  client/src/components/basic/avatar/index.tsx
  client/src/components/basic/index.ts
  client/src/components/basic/label/index.tsx
  client/src/components/basic/label/label.module.scss
  client/src/components/common/header/header.module.scss
  client/src/components/common/header/index.tsx
  client/src/components/common/index.ts
  client/src/components/index.ts
Labels: enhancement

#22 add Code & Markdown Editor Component
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/common/enum/app/index.ts
  client/src/common/enum/app/task-page/create-code.ts
  client/src/common/enum/app/task-page/icons.ts
  client/src/common/enum/app/task-page/index.ts
  client/src/common/enum/app/task-page/markdown.ts
  client/src/common/enum/app/task-page/type-task-tab.tsx
  client/src/common/enum/index.ts
  client/src/common/index.ts
  client/src/components/index.ts
  client/src/components/pages/create-task/common/create-tabs/create-code/index.tsx
  client/src/components/pages/create-task/common/create-tabs/create-tabs.tsx
  client/src/components/pages/create-task/common/create-tabs/create-text/index.tsx
  client/src/components/pages/create-task/common/create-tabs/create-text/styles.module.scss
  client/src/components/pages/create-task/common/create-tabs/header/index.tsx
  client/src/components/pages/create-task/common/create-tabs/header/styles.module.scss
  client/src/components/pages/create-task/common/create-tabs/index.ts
  client/src/components/pages/create-task/common/create-tabs/markdown/index.tsx
  client/src/components/pages/create-task/common/create-tabs/markdown/styles.module.scss
  client/src/components/pages/create-task/common/create-tabs/styles.module.scss
  client/src/components/pages/create-task/common/create-tabs/tab-content.tsx
  client/src/components/pages/create-task/common/create-tabs/types.ts
  client/src/components/pages/create-task/common/index.ts
  client/src/components/pages/create-task/index.ts
  client/src/components/pages/index.ts
  package-lock.json
Labels: enhancement

#31 Image uploading services
  client/src/containers/example/index.tsx
  client/src/helpers/call-api.helper.ts
  client/src/services/images.service.ts
  server/.env.example
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/api/images.controller.ts
  server/src/api/index.ts
  server/src/common/constants/config/config-variables-name.ts
  server/src/common/constants/images.constants.ts
  server/src/common/constants/index.ts
  server/src/common/enum/api/api-path.ts
  server/src/common/enum/app/env-enum.ts
  server/src/common/enum/http-codes.ts
  server/src/common/enum/index.ts
  server/src/data/repositories/images.repository.ts
  server/src/data/repositories/index.ts
  server/src/helpers/check-config/check-config.ts
  server/src/helpers/check-config/index.ts
  server/src/helpers/env.helper.ts
  server/src/helpers/index.ts
  server/src/helpers/multer.helper.ts
  server/src/helpers/token/create-token.ts
  server/src/index.ts
  server/src/middleware/error-handler/error-handler-middleware.ts
  server/src/middleware/image.middleware.ts
  server/src/middleware/index.ts
  server/src/services/images.service.ts
  server/src/services/index.ts
  server/src/types/file.ts
  server/src/types/index.ts
Labels: enhancement

#35 add porfile tasks tab
  client/src/components/basic/avatar/avatar.module.scss
  client/src/components/basic/button/button.module.scss
  client/src/components/common/challenge/challenge-header/challenge-header.module.scss
  client/src/components/common/challenge/challenge-header/index.tsx
  client/src/components/common/challenge/challenge-stats/index.tsx
  client/src/components/common/challenge/index.tsx
  client/src/components/common/challenge/types.d.ts
  client/src/components/common/form-input/form-input.module.scss
  client/src/components/index.ts
  client/src/components/modals/modal/modal.module.scss
  client/src/components/pages/change-password/change-password.module.scss
  client/src/components/pages/forgot-password/forgot-password.module.scss
  client/src/components/pages/index.ts
  client/src/components/pages/profile/profile-tasks/index.tsx
  client/src/components/pages/profile/profile-tasks/side-bar.ts/styles.module.scss
  client/src/components/pages/profile/profile-tasks/side-bar/index.tsx
  client/src/components/pages/profile/profile-tasks/side-bar/styles.module.scss
  client/src/components/pages/profile/profile-tasks/styles.module.scss
  client/src/components/pages/profile/profile-tasks/tasks/index.tsx
  client/src/components/pages/profile/profile-tasks/tasks/styles.module.scss
  client/src/components/pages/search-page/index.tsx
  client/src/components/pages/search-page/search-task/search-task.module.scss
  client/src/components/pages/sign-in/cover-layout/cover.module.scss
  client/src/components/pages/sign-in/form-field/form-field.module.scss
  client/src/components/pages/sign-in/password-field/password-input.module.scss
  client/src/components/pages/sign-in/separator/separator.module.scss
  client/src/components/pages/sign-in/sign-in.module.scss
  client/src/containers/profile/config.ts
  client/src/containers/profile/index.tsx
  client/src/containers/profile/logic/models.ts
  client/src/containers/profile/tabs/index.ts
  client/src/containers/profile/tabs/tasks/index.tsx
  client/src/containers/profile/tabs/tasks/mocks.ts
Labels: enhancement

#32 add jwt-authorization
  client/package-lock.json
  client/package.json
  client/src/components/basic/private-route/index.tsx
  client/src/components/basic/public-route/index.tsx
  client/src/components/index.ts
  client/src/constants/local-storage-keys.ts
  client/src/constants/services/http-methods.ts
  client/src/constants/services/index.ts
  client/src/containers/example/index.tsx
  client/src/containers/routing/index.tsx
  client/src/containers/routing/logic/action-types.ts
  client/src/containers/routing/logic/actions.ts
  client/src/containers/routing/logic/reducer.ts
  client/src/containers/routing/logic/saga.ts
  client/src/containers/routing/logic/state.ts
  client/src/containers/routing/test-private.tsx
  client/src/enum/api/auth-api-path.ts
  client/src/enum/api/index.ts
  client/src/enum/index.ts
  client/src/helpers/call-api.helper.ts
  client/src/helpers/error/app-error.ts
  client/src/helpers/error/index.ts
  client/src/helpers/error/unauthorized-error.ts
  client/src/hooks/useAppSelector.ts
  client/src/redux/root-reducer.ts
  client/src/redux/root-saga.ts
  client/src/services/auth/access-token.ts
  client/src/services/auth/auth-services.ts
  client/src/services/auth/index.ts
  client/src/services/http/http-services.ts
  client/src/services/http/index.ts
  client/src/services/images.service.ts
  client/src/services/index.ts
  client/src/typings/helpers.d.ts
  client/src/typings/root-state.ts
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/auth/auth-api.ts
  server/src/common/constants/api/white-routes.ts
  server/src/common/constants/helpers/error/code-errors.ts
  server/src/common/constants/index.ts
  server/src/common/enum/api/auth-api-path.ts
  server/src/common/enum/app/env-enum.ts
  server/src/config/cookie-session/cookie-config.ts
  server/src/config/index.ts
  server/src/helpers/token/create-token.ts
  server/src/helpers/token/index.ts
  server/src/helpers/token/verify-token.ts
  server/src/index.ts
  server/src/services/auth/auth-service.ts
Labels: enhancement

#39 fix bug
  client/src/components/common/challenge/challenge-stats/challenge-stats.module.scss
  client/src/components/pages/profile/profile-tasks/side-bar.ts/styles.module.scss
  client/src/components/pages/profile/profile-tasks/styles.module.scss
  client/src/components/pages/profile/profile-tasks/tasks/styles.module.scss
Labels: bug

#48 fix/jwt-token
  server/src/api/auth/auth-api.ts
  server/src/data/index.ts
  server/src/helpers/cookie-session.ts
  server/src/helpers/index.ts
Labels: bug

#44 Feature/crud task
  server/package-lock.json
  server/package.json
  server/src/api/auth/auth-api.ts
  server/src/api/clan/clan-api.ts
  server/src/api/index.ts
  server/src/api/task/task-api.ts
  server/src/common/constants/data/model/index.ts
  server/src/common/constants/data/model/task/task.ts
  server/src/common/constants/errors/code-errors.ts
  server/src/common/constants/errors/errors.ts
  server/src/common/constants/errors/index.ts
  server/src/common/constants/helpers/index.ts
  server/src/common/constants/index.ts
  server/src/common/enum/api/api-path.ts
  server/src/common/enum/api/index.ts
  server/src/common/enum/api/task-api-path.ts
  server/src/data/models/index.ts
  server/src/data/models/task/index.ts
  server/src/data/models/task/task-model.ts
  server/src/data/models/user/profile-clan-model.ts
  server/src/data/models/user/user-model.ts
  server/src/data/repositories/abstract/index.ts
  server/src/data/repositories/clan/clan-repository.ts
  server/src/data/repositories/index.ts
  server/src/data/repositories/task/task-repository.ts
  server/src/data/repositories/user/user-repository.ts
  server/src/middleware/check/clan/clan-id-middleware.ts
  server/src/middleware/check/clan/clan-permission-middleware.ts
  server/src/middleware/check/clan/index.ts
  server/src/middleware/check/index.ts
  server/src/middleware/check/task/task-id-middleware.ts
  server/src/middleware/index.ts
  server/src/middleware/validation/index.ts
  server/src/middleware/validation/task-validation/index.ts
  server/src/middleware/validation/task-validation/task-id-schema.ts
  server/src/middleware/validation/task-validation/task-schema.ts
  server/src/services/auth/auth-service.ts
  server/src/services/clan/clan-service.ts
  server/src/services/index.ts
  server/src/services/task/task-service.ts
  server/src/types/clan/clan-fields.ts
  server/src/types/clan/index.ts
  server/src/types/express..d.ts
  server/src/types/index.ts
  server/src/types/user/index.ts
  server/src/types/user/user-fields.ts
Labels: enhancement, conflicts

#41 Feature/home page
  client/package-lock.json
  client/src/components/common/next-task/nextTask.module.scss
  client/src/components/pages/home/components/community/index.tsx
  client/src/components/pages/home/components/feed/index.tsx
  client/src/containers/home-page/index.tsx
  server/package-lock.json
Labels: conflicts

#36 Patch/mailer
  client/package-lock.json
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/auth/auth-api.ts
  server/src/common/enum/app/env-enum.ts
  server/src/data/mailer-texts/index.ts
  server/src/data/mailer-texts/texts.ts
  server/src/helpers/mailer/index.ts
  server/src/helpers/mailer/mailer.ts
Labels: conflicts

#24 Feature/task instructions
  client/package-lock.json
  client/src/components/common/index.ts
  client/src/components/common/task-instructions/components/details/index.tsx
  client/src/components/common/task-instructions/components/details/task-details.scss
  client/src/components/common/task-instructions/components/statistics/index.tsx
  client/src/components/common/task-instructions/components/statistics/statistics.module.scss
  client/src/components/common/task-instructions/config.ts
  client/src/components/common/task-instructions/index.tsx
  client/src/components/common/task-instructions/mockData.tsx
  client/src/components/common/task-instructions/task-instructions.module.scss
  client/src/components/index.ts
  client/src/constants/routes.ts
  client/src/containers/routing/index.tsx
  client/src/containers/task-page/index.tsx
Labels: conflicts

#42 Patch/create task layout 2
  .prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/assets/icons/beta-icon.svg
  client/src/assets/icons/books-icon.svg
  client/src/assets/icons/info-popover.svg
  client/src/assets/icons/practice-icon.svg
  client/src/assets/icons/rank-up-icon.svg
  client/src/assets/icons/shuffle-icon.svg
  client/src/components/basic/index.ts
  client/src/components/basic/info-popover/index.tsx
  client/src/components/basic/info-popover/info-popover.module.scss
  client/src/components/basic/option/index.tsx
  client/src/components/basic/option/option.module.scss
  client/src/components/basic/select/index.tsx
  client/src/components/basic/select/interface.ts
  client/src/components/basic/select/select.module.scss
  client/src/components/basic/switch/index.tsx
  client/src/components/basic/switch/switch.module.scss
  client/src/components/index.ts
  client/src/components/pages/create-task/create-task-settings/create-task-settings.module.scss
  client/src/components/pages/create-task/create-task-settings/index.tsx
  client/src/components/pages/create-task/index.ts
  client/src/components/pages/create-task/radio-item/index.tsx
  client/src/components/pages/create-task/radio-item/radio-item.module.scss
  client/src/components/pages/index.ts
  client/src/containers/create-new-task/create-task-settings/create-task-settings.tsx
  client/src/containers/create-new-task/create-task-settings/index.ts
  client/src/containers/create-new-task/create-task.tsx
  client/src/containers/create-new-task/index.ts
  client/src/containers/create-new-task/logic/action-types.ts
  client/src/containers/create-new-task/logic/actions.ts
  client/src/containers/create-new-task/logic/models.ts
  client/src/containers/create-new-task/logic/reducer.ts
  client/src/containers/create-new-task/logic/state.ts
  client/src/containers/create-new-task/mock.ts
  client/src/containers/example/index.tsx
  client/src/containers/routing/index.tsx
  client/src/redux/root-reducer.ts
  client/src/typings/root-state.ts
Labels: conflicts

#56 GitHub Auth API
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/github.router.ts
  server/src/api/images.router.ts
  server/src/api/index.ts
  server/src/common/constants/api/white-routes.ts
  server/src/common/enum/api/api-path.ts
  server/src/common/enum/api/github-api-path.ts
  server/src/common/enum/api/index.ts
  server/src/common/enum/app/env-enum.ts
  server/src/config/passport.ts
  server/src/data/models/user/user-model.ts
  server/src/data/repositories/user/user-repository.ts
  server/src/helpers/crypt/crypt-compare-helper.ts
  server/src/helpers/crypt/encrypt-helper.ts
  server/src/helpers/github.helper.ts
  server/src/helpers/index.ts
  server/src/services/github.service.ts
  server/src/services/index.ts
Labels: enhancement

#38 Feature/swagger
  server/package-lock.json
  server/package.json
  server/src/api/auth/auth-api.ts
  server/src/api/clan/clan-api.ts
  server/src/common/enum/api/api-path.ts
  server/src/common/enum/app/env-enum.ts
  server/src/config/swagger.ts
  server/src/helpers/mailer/index.ts
  server/src/helpers/mailer/mailer.ts
  server/src/index.ts
Labels: documentation, conflicts

#59 Feature/social
  client/src/assets/icons/user.svg
  client/src/components/common/index.ts
  client/src/components/common/social/index.tsx
  client/src/components/common/social/social.module.scss
  client/src/components/index.ts
  client/src/components/pages/home/components/community-user/index.tsx
  client/src/components/pages/index.ts
  client/src/components/pages/profile/profile-social-list/index.tsx
  client/src/components/pages/profile/profile-social-list/styles.module.scss
  client/src/components/pages/profile/profile-tab-with-sidebar/index.tsx
  client/src/components/pages/profile/profile-tab-with-sidebar/side-bar/index.tsx
  client/src/components/pages/profile/profile-tab-with-sidebar/side-bar/styles.module.scss
  client/src/components/pages/profile/profile-tab-with-sidebar/styles.module.scss
  client/src/components/pages/profile/profile-tasks/index.tsx
  client/src/components/pages/profile/profile-tasks/tasks/index.tsx
  client/src/components/pages/profile/profile-tasks/tasks/styles.module.scss
  client/src/containers/profile/index.tsx
  client/src/containers/profile/tabs/index.ts
  client/src/containers/profile/tabs/social/index.tsx
  client/src/containers/profile/tabs/social/mocks.ts
  client/src/containers/profile/tabs/tasks/index.tsx
  client/src/typings/common/IUser.tsx
Labels: enhancement

#89 fix/IClanFields
  server/src/types/index.ts
Labels: bug

#88 Finish create-task page
  client/package-lock.json
  client/src/components/basic/change-theme/change-theme.module.scss
  client/src/components/basic/change-theme/change-theme.tsx
  client/src/components/basic/change-theme/index.ts
  client/src/components/basic/public-route/index.tsx
  client/src/components/basic/select/index.tsx
  client/src/components/basic/select/select.module.scss
  client/src/components/basic/switch/switch.module.scss
  client/src/components/common/main-sidebar/main-sidebar.module.scss
  client/src/components/common/task-instructions/task-instructions.module.scss
  client/src/components/pages/clans/clan/clan.module.scss
  client/src/components/pages/clans/clans/clans.module.scss
  client/src/components/pages/create-task/buttons-block/buttons-block.module.scss
  client/src/components/pages/create-task/buttons-block/buttons-block.scss
  client/src/components/pages/create-task/buttons-block/buttons-block.tsx
  client/src/components/pages/create-task/buttons-block/index.ts
  client/src/components/pages/create-task/common/create-tabs/create-tabs.tsx
  client/src/components/pages/create-task/common/create-tabs/markdown/index.tsx
  client/src/components/pages/create-task/common/create-tabs/styles.module.scss
  client/src/components/pages/create-task/common/create-tabs/tab-content.tsx
  client/src/components/pages/create-task/common/create-tabs/types.ts
  client/src/components/pages/create-task/create-task-settings/create-task-settings.module.scss
  client/src/components/pages/create-task/index.ts
  client/src/components/pages/create-task/radio-item/radio-item.module.scss
  client/src/components/pages/home/home-page.module.scss
  client/src/components/pages/index.ts
  client/src/components/pages/profile/profile.module.scss
  client/src/components/pages/search-page/search-page.module.scss
  client/src/components/pages/setting/setting-page.module.scss
  client/src/containers/create-new-task/create-task-settings/create-task-settings.tsx
  client/src/containers/create-new-task/create-task.module.scss
  client/src/containers/create-new-task/create-task.scss
  client/src/containers/create-new-task/create-task.tsx
  client/src/containers/create-new-task/logic/action-types.ts
  client/src/containers/create-new-task/logic/actions.ts
  client/src/containers/create-new-task/logic/reducer.ts
  client/src/containers/create-new-task/logic/state.ts
  client/src/containers/private-route/index.tsx
  client/src/styles/index.scss
Labels: bug, enhancement, open

#91 fix email
  server/.env.example
  server/src/common/enum/app/env-enum.ts
  server/src/helpers/mailer/mailer.ts
Labels: bug

#111 fix iuserfield
  server/src/services/users/users-service.ts
  server/src/types/user/user-fields.ts
Labels: bug

#112 fix task entity
  server/src/data/models/task/task-model.ts
Labels: bug

#114 fix task
  server/src/data/repositories/index.ts
  server/src/services/task/task-service.ts
Labels: bug

#115 Fix image service
  client/src/services/images.service.ts
Labels: bug

#129 Feature/rabbitmq
  client/src/components/basic/checkbox/index.tsx
  client/src/components/pages/search-page/search-task/index.tsx
  client/src/constants/task.ts
  client/src/containers/recover-password/change-password.tsx
  client/src/containers/search-page/logic/state.ts
  client/src/containers/search-page/mapSearchData.ts
  server/.env.example
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/src/api/task/task-api.ts
  server/src/common/enum/app/env-enum.ts
  server/src/config/amqplib.ts
  server/src/config/index.ts
  server/src/data/repositories/tag/tag-repository.ts
  server/src/data/repositories/task/task-repository.ts
  server/src/index.ts
  server/src/middleware/validation/task-validation/task-schema.ts
  server/src/middleware/validation/task-validation/task-search-validation.ts
  server/src/middleware/validation/task-validation/task-tags-validation.ts
  server/src/services/solution/solution-service.ts
  server/src/services/task/task-service.ts
Labels: enhancement

#131 fix amqp
  server/src/config/index.ts
  server/src/services/solution/solution-service.ts
Labels: bug

#139 fix/center search page
  client/src/components/pages/search-page/search-page.module.scss
Labels: bug

#153 fix header dropdown
  client/src/components/basic/avatar/avatar.module.scss
  client/src/components/basic/checkbox/checkbox.module.scss
  client/src/components/basic/tag-list/tag-list.module.scss
  client/src/components/common/challenge/types.d.ts
  client/src/components/common/header/header.module.scss
  client/src/components/common/header/index.tsx
  client/src/components/pages/not-found/not-found.module.scss
  client/src/components/pages/search-page/challenges-list/index.tsx
  client/src/components/pages/search-page/search-task/search-task.module.scss
  client/src/components/pages/setting/components/delete-account/delete-account.module.scss
  client/src/components/pages/sign-up/sign-up.module.scss
  client/src/containers/header/index.tsx
  client/src/containers/header/items-dropdown.ts
  client/src/containers/header/mock.ts
  client/src/containers/next-task/index.tsx
  client/src/containers/profile/tabs/index.ts
  client/src/containers/profile/tabs/social/index.tsx
  client/src/containers/profile/tabs/tasks/mocks.ts
  client/src/services/create-task.service.ts
  client/src/services/http/http-services.ts
Labels: bug

#154 fix
  client/src/components/common/challenge/challenge-stats/index.tsx
  client/src/containers/search-page/mapSearchData.ts
Labels: bug

#157 Feature/create testing service
  server/src/api/index.ts
  server/src/api/test/test-api.ts
  server/src/common/constants/api/white-routes.ts
  server/src/common/constants/errors/code-errors.ts
  server/src/common/enum/api/api-path.ts
  server/src/common/enum/api/index.ts
  server/src/common/enum/api/solution-api-path.ts
  server/src/common/enum/api/test-api-path.ts
  server/src/common/enum/app/env-enum.ts
  server/src/config/amqplib.ts
  server/src/config/index.ts
  server/src/services/solution/solution-service.ts
  testing-service/.env.example
  testing-service/.eslintrc.json
  testing-service/.prettierrc.json
  testing-service/Dockerfile
  testing-service/package-lock.json
  testing-service/package.json
  testing-service/src/common/api.ts
  testing-service/src/common/constants.ts
  testing-service/src/common/env-enum.ts
  testing-service/src/common/http-methods.ts
  testing-service/src/config/amqp-mocks.ts
  testing-service/src/config/amqplib.ts
  testing-service/src/helpers/call-api.ts
  testing-service/src/helpers/create-token.ts
  testing-service/src/helpers/dot-env.ts
  testing-service/src/helpers/path.ts
  testing-service/src/helpers/run-test.ts
  testing-service/src/index.ts
  testing-service/test/test.js
  testing-service/tsconfig.json
Labels: enhancement

#158 Fix users route
  client/src/components/common/notification/helper.tsx
  client/src/constants/routes.ts
  client/src/containers/header/items-dropdown.ts
  client/src/containers/routing/index.tsx
Labels: bug

#166 fix/challenge-tag
  client/package-lock.json
  client/src/components/common/challenge/index.tsx
  client/src/components/common/challenge/types.d.ts
Labels: bug

#176 Profile | Solution tab Layout
  client/src/components/basic/rank/beta.tsx
  client/src/components/basic/rank/rank.module.scss
  client/src/components/common/collection/index.tsx
  client/src/components/common/header/header.module.scss
  client/src/components/common/index.ts
  client/src/components/common/task-solutions/config.ts
  client/src/components/common/task-solutions/index.tsx
  client/src/components/common/task-solutions/skeleton.tsx
  client/src/components/common/task-solutions/task-solutions.module.scss
  client/src/components/pages/profile/profile-collections-list/index.tsx
  client/src/components/pages/profile/profile-skeleton-list/index.tsx
  client/src/components/pages/profile/profile-skeleton-list/profile-skeleton-list.module.scss
  client/src/components/pages/profile/profile-tab-with-sidebar/side-bar/styles.module.scss
  client/src/containers/profile/config.ts
  client/src/containers/profile/index.tsx
  client/src/containers/profile/tabs/collections/index.tsx
  client/src/containers/profile/tabs/collections/mocks.ts
  client/src/containers/profile/tabs/solutions/index.tsx
  client/src/containers/profile/tabs/solutions/mocks.ts
  client/src/hooks/useAppSelector.ts
  client/src/services/collections.service.ts
  client/src/services/solutions.service.ts
  client/src/styles/index.scss
  client/src/styles/variables.scss
  client/src/typings/common/loader.ts
  client/src/typings/common/solution.ts
  client/src/typings/common/task.ts
  client/src/typings/webapi.d.ts
Labels: enhancement

#174 Feature/train task
  client/package-lock.json
  client/src/common/enum/app/solutions/solution-status.ts
  client/src/common/enum/app/tasks/task-status.ts
  client/src/components/common/code-editor/code-editor.module.scss
  client/src/components/common/code-editor/index.tsx
  client/src/components/common/tabs/index.tsx
  client/src/components/common/tabs/tabs.module.scss
  client/src/components/index.ts
  client/src/components/pages/index.ts
  client/src/components/pages/task-train/components/index.ts
  client/src/components/pages/task-train/components/task-statistic/index.tsx
  client/src/components/pages/task-train/components/task-statistic/task-statistic.module.scss
  client/src/components/pages/task-train/index.tsx
  client/src/components/pages/task-train/task-train.module.scss
  client/src/constants/routes.ts
  client/src/constants/services/api-routes.ts
  client/src/constants/services/index.ts
  client/src/containers/create-new-task/create-task.tsx
  client/src/containers/profile/tabs/collections/mocks.ts
  client/src/containers/profile/tabs/solutions/mocks.ts
  client/src/containers/routing/index.tsx
  client/src/containers/task-train/index.tsx
  client/src/containers/task-train/logic/action-types.ts
  client/src/containers/task-train/logic/actions.ts
  client/src/containers/task-train/logic/reducer.ts
  client/src/containers/task-train/logic/saga.ts
  client/src/containers/task-train/logic/state.ts
  client/src/containers/user/logic/action-types.ts
  client/src/containers/user/logic/actions.ts
  client/src/containers/user/logic/reducer.ts
  client/src/redux/root-reducer.ts
  client/src/redux/root-saga.ts
  client/src/services/solutions.service.ts
  client/src/services/tasks.service.ts
  client/src/typings/root-state.ts
  client/src/typings/webapi.d.ts
  server/src/api/task/solution/solution-api.ts
  server/src/common/enum/api/solution-api-path.ts
  server/src/data/repositories/task/task-repository.ts
  server/src/services/solution/solution-service.ts
Labels: conflicts

#222 Connect profile/solutions to the server
  client/src/components/common/collection/collection.module.scss
  client/src/components/common/task-solutions/index.tsx
  client/src/components/common/task-solutions/task-solutions.module.scss
  client/src/containers/profile/tabs/solutions/index.tsx
  client/src/containers/profile/tabs/solutions/mocks.ts
  client/src/services/solutions.service.ts
  client/src/typings/webapi.d.ts
  server/src/api/task/task-api.ts
  server/src/common/enum/api/task-api-path.ts
  server/src/data/migrations/1630081543408-solutions.ts
  server/src/middleware/validation/index.ts
  server/src/middleware/validation/task-validation/index.ts
  server/src/middleware/validation/task-validation/task-with-solutions.schema.ts
  server/src/services/task/task-service.ts
Labels: enhancement

#227 Fix / connect github link on User's profile page
  client/src/components/pages/profile/profile-bio/index.tsx
  client/src/containers/profile/logic/saga.ts
Labels: bug
